apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: rewrite.nginx
  annotations:
     kubernetes.io/ingress.class: nginx
   #  nginx.ingress.kubernetes.io/use-regex: "true"
  #   nginx.ingress.kubernetes.io/enable-cors: "true"
     nginx.ingress.kubernetes.io/rewrite-target: "https://fxkjnj.com"
spec:
  rules:
  - host: rewrite.nginx.com
    http:
      paths:
      - path: /(.*)
        pathType: Prefix
        backend:
          serviceName: web-1
          servicePort: 80
